version: '3.9'
services:
  server:
    build: server
    volumes:
      - .:/code
      - gocacheserver:/go
    command: go run main.go -server -l 443
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun
    ports:
      - "443:443"
volumes:
  gocacheserver:
